import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ReportView({ findings }) {
    const confirmed = findings.filter((f) => f.confidence === "confirmed");
    const inferred = findings.filter((f) => f.confidence === "inferred");
    const uncertain = findings.filter((f) => f.confidence === "uncertain");
    return (_jsxs("div", { className: "report", children: [_jsx("h1", { children: "Investigation Report" }), _jsxs("dl", { className: "kvs", children: [_jsx("dt", { children: "case" }), _jsx("dd", { children: "untitled" }), _jsx("dt", { children: "generated" }), _jsx("dd", { children: new Date().toISOString() }), _jsx("dt", { children: "findings" }), _jsxs("dd", { children: [findings.length, " total \u00B7 ", confirmed.length, " confirmed \u00B7 ", inferred.length, " inferred \u00B7", " ", uncertain.length, " uncertain"] })] }), _jsx("h2", { children: "Confirmed" }), confirmed.length === 0 ? (_jsx("p", { children: "No confirmed findings yet." })) : (confirmed.map((f) => _jsx(FindingBlock, { finding: f }, f.id))), _jsx("h2", { children: "Inferred" }), inferred.length === 0 ? (_jsx("p", { children: "No inferences yet." })) : (inferred.map((f) => _jsx(FindingBlock, { finding: f }, f.id))), _jsx("h2", { children: "Flagged for Review" }), uncertain.length === 0 ? (_jsx("p", { children: "Nothing flagged." })) : (uncertain.map((f) => _jsx(FindingBlock, { finding: f }, f.id)))] }));
}
function FindingBlock({ finding }) {
    return (_jsxs("div", { style: { marginBottom: 16 }, children: [_jsxs("div", { style: { display: "flex", gap: 8, alignItems: "center" }, children: [_jsx("span", { className: `tag ${finding.confidence}`, children: finding.confidence }), _jsx("strong", { style: { fontWeight: 500 }, children: finding.title })] }), _jsx("p", { style: { color: "var(--fg-1)", margin: "6px 0 4px" }, children: finding.detail ?? "No detail recorded." }), _jsxs("div", { style: { fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--fg-2)" }, children: ["source: ", finding.source, finding.functionCallId ? ` · call_id: ${finding.functionCallId}` : "", ` · t: ${finding.timestamp}`] })] }));
}
